langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-04c8dea728a841d589c523cea45d6fb7
        model-name: qwen-max
      embedding-model:
        model-name: text-embedding-v4
        api-key: sk-04c8dea728a841d589c523cea45d6fb7

bigmodel:
  api-key: e17eb1f1fe784a7fb44c30857139832f.7qIMjyLpoNtAOVS1

logging:
  level:
    dev:
      langchain4j: DEBUG